# Following the instruction from https://docs.namada.net/introduction/install/source
# This is so we can do the localnet setup
# podman build --no-cache -t namada:v0.31.10-inst -f Dockerfile.inst .
FROM docker.io/rust:1.81-slim-bookworm AS builder

ARG GIT_SHA
RUN [ -z "$GIT_SHA" ] && echo "GIT_SHA is required" && exit 1 || true

WORKDIR /namada

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    make \
    git-core \
    libssl-dev \
    pkg-config \
    libclang-13-dev \
    build-essential \
    protobuf-compiler \
    libprotobuf-dev \
    libudev-dev \
    curl \
    wget \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ADD --keep-git-dir=true https://github.com/anoma/namada.git#$GIT_SHA .

# Be aware the patch could potentially be version dependent
# getting rid of the sudo
COPY ./scripts_get_cometbft.patch .
RUN git apply scripts_get_cometbft.patch

RUN make cometbft

# Instrumentation steps
RUN wget -O /usr/lib/libvoidstar.so https://antithesis.com/assets/instrumentation/libvoidstar.so

RUN LD_LIBRARY_PATH=/usr/lib/libvoidstar.so \
    RUSTFLAGS=" \
      -Ccodegen-units=1 \
      -Cpasses=sancov-module \
      -Cllvm-args=-sanitizer-coverage-level=3 \
      -Cllvm-args=-sanitizer-coverage-trace-pc-guard \
      -Clink-args=-Wl,--build-id  \
      -L/usr/lib/libvoidstar.so \
      -lvoidstar" \
    make build

RUN ldd target/release/namada | grep "libvoidstar"
RUN nm target/release/namada | grep "sanitizer_cov_trace_pc_guard"

RUN mkdir -p /root/.masp-params \
    && curl -o /root/.masp-params/masp-spend.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-spend.params?raw=true \
    && curl -o /root/.masp-params/masp-output.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-output.params?raw=true \
    && curl -o /root/.masp-params/masp-convert.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-convert.params?raw=true

# Try to slim down the runner
FROM docker.io/rust:1.81-slim-bookworm

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV NAMADA_MASP_PARAMS_DIR=/root/.masp-params

COPY --from=builder /root/.masp-params/* /root/.masp-params/
COPY --from=builder /namada/target/release/namada* /usr/local/bin/
COPY --from=builder /usr/local/bin/cometbft /usr/local/bin/cometbft
COPY --from=builder /usr/lib/libvoidstar.so /usr/lib/libvoidstar.so